name: Publish Docs 
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build and Deploy to gh-pages with MkDocs
      run: mkdocs gh-deploy --force 