name: Lint and Test code
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'    
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linters 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install linting dependencies only
      run: |
        pip install --upgrade pip
        pip install black==23.3.0 isort==5.10.1 flake8==6.0.0

    - name: Run Black
      run: black --check .

    - name: Run isort
      run: isort --check-only .

    - name: Run flake8
      run: flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    needs: lint 

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4 

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pytest and others 
        run: |
          pip install --upgrade pip
          pip install ".[test]" 
      
      - name: Run tests
        run: pytest tests